# Generated by Django 5.1.1 on 2024-12-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('sending', 'Sending'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sending', max_length=10),
        ),
    ]
