# Generated by Django 5.1 on 2024-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_recipient_chatmessage_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
